#general
#node id is 0-indexed
n_peers: 4
# n_peers = 3f + 1
f: 1
# attacker:
num_malicious: 2
# identifier:
num_transcripts_avail: 2

#initialization (break things if they are not set to 0)
initialized_seq_num: 0
initialized_view_num: 0
initialized_primary: 0

work_window_size: 10
idle_timer_limit: 5
commit_timer_limit: 5
view_change_duration: 5
simulator_id: 25

# both received and send
max_message_num_per_round: 4

# specify obs size and action size

episode_limit: 500

# reward
identifier_reward_consensus_reached: 0
attacker_reward_consensus_reached: 0
identifier_reward_consensus_breached: -5
attacker_reward_consensus_breached: 5
identifier_reward_correct_detection: 3
attacker_reward_correct_detection: -3
identifier_reward_incorrect_detection: -3
attacker_reward_incorrect_detection: 1
attacker_reward_invalid_certificate: -0.1

# game
terminate_after_consensus_breached: False
steps_per_new_client_request: 5
