#general
#node id is 0-indexed
n_peers:
f:

#initialization
initialized_seq_num: 0
initialized_view_num: 0
initialized_primary: 0

work_window_size:
idel_timer_limit:
commit_timer_limit:
view_change_duration:
simulator_id: