#general
#node id is 0-indexed
n_peers: 4
# n_peers = 3f + 1
f: 1
# attacker:
num_malicious: 2
# identifier:
num_transcripts_avail: 2

#initialization (break things if they are not set to 0)
initialized_seq_num: 0
max_seq_num: 5
initialized_view_num: 0
max_view_num: 5  # make sure not possible to exceed
initialized_primary: 0

work_window_size: 2
idle_timer_limit: 20
commit_timer_limit: 20
view_change_duration: 15
simulator_id: 25

# both received and send
max_message_num_per_round: 1

# specify obs size and action size

episode_limit: 100

# reward
identifier_reward_consensus_reached: 0
attacker_reward_consensus_reached: 0
identifier_reward_consensus_breached: -0.5
attacker_reward_consensus_breached: 0.5
identifier_reward_correct_detection: 0.5
attacker_reward_correct_detection: -0.3
identifier_reward_incorrect_detection: -2
attacker_reward_incorrect_detection: 0
attacker_reward_invalid_certificate: -0.01

# game
terminate_after_consensus_breached: True
steps_per_new_client_request: 5

# client vals (break things if changed)
total_client_vals: 2

n_agents: 2